
CREATE TABLE carriermgmt.rail_stop_header (
	stop_id bigserial NOT NULL,
	train_number varchar(10) NOT NULL,
	train_name varchar(255) not null,
	section_id varchar(10)	not null,
	section_name varchar(20) null,
	name_of_division varchar(10) null,
	beat_from_station varchar(20) null,
	beat_from_station_office_id int8 null,
	beat_to_station varchar(20) null,
	beat_to_station_office_id int8 null,
	sequence_number int8 not null,
	stopage_station_name varchar(50) NOT NULL,
	stoppage_station_office_id int8 null,
	arrival_time time null,
	departure_time time null,
	transit_time time null,
	stay_duration time null,
	created_by varchar(50) NOT NULL,
	updated_by varchar(50) NULL,
	deleted_by varchar(50) NULL,
	created_date timestamp NULL,
	updated_date timestamp NULL,
	deleted_date timestamp NULL,
	stopage_onboard_office_id int8 NOT NULL,
	CONSTRAINT rail_stop_header_pkey PRIMARY KEY (stop_id)
);
CREATE TABLE carriermgmt.section_header (
	section_id bigserial NOT NULL,
	train_number varchar(10) NOT NULL,
	train_name varchar(255) not null,
	section_name varchar(20) null,
	name_of_division varchar(10) null,
	beat_from_station varchar(20) null,
	beat_from_station_office_id int8 null,
	beat_to_station varchar(20) null,
	beat_to_station_office_id int8 null,
--	sequence_number int8 not null,
--	stopage_station_name varchar(50) NOT NULL,
--	stoppage_station_office_id int8 null,
--	arrival_time time null,
--	departure_time time null,
--	transit_time time null,
--	stay_duration time null,
	created_by varchar(50) NOT NULL,
	updated_by varchar(50) NULL,
	deleted_by varchar(50) NULL,
	created_date timestamp NULL,
	updated_date timestamp NULL,
	deleted_date timestamp NULL,
	stopage_onboard_office_id int8 NOT NULL,
	CONSTRAINT section_header_pkey PRIMARY KEY (section_id)
);

CREATE TABLE carriermgmt.rail_header (
	rail_id bigserial NOT NULL,
	railway_zone varchar(10) not null,
	payment_circle varchar(10) not null,
	payment_circle_code varchar(20) not null,
	train_number varchar(10) NOT NULL,
	train_name varchar(255) not null,	
	from_station varchar(50) NOT NULL,
	to_station varchar(50) NOT NULL,
	sanctioned_seating_capacity int8 NOT NULL,
	rail_status carriermgmt."rail_status_enum" NOT NULL,
	created_by varchar(50) NOT NULL,
	updated_by varchar(50) NULL,
	deleted_by varchar(50) NULL,
	created_date timestamp NULL,
	updated_date timestamp NULL,
	deleted_date timestamp NULL,
	contract_from_date timestamp NOT NULL,
	contract_to_date timestamp NOT NULL,
	rail_onboard_office_id int8 NOT NULL,
	CONSTRAINT rail_header_pkey PRIMARY KEY (train_number)
);
