CREATE TABLE carriermgmt.schedule_mc_stop_sequences_stg (
	schedule_id int8 NOT NULL,
	sequence_number int8 NOT NULL,
	stop_office_id int8 NOT NULL,
	stop_office_name varchar(50) NULL,
	distance_from_prev_stop float8 NULL,
	arrival_time timestamp NULL,
	departure_time timestamp NOT NULL,
	transit_time int4 NULL,
	stay_duration int4 NULL,
	cut_of_time int4 NULL,
	office_location_latitude numeric(10, 8) NULL,
	office_location_longitude numeric(10, 8) NULL,
	division_id varchar(255) NULL,
	circle_id varchar(255) NULL,
	section_id varchar(255) NULL,
	section_beat_name varchar(255) NULL,
	station_code varchar(255) NULL,
	station_name varchar(255) NULL,
	created_by varchar(50) NOT NULL,
	created_date timestamp DEFAULT now() NOT NULL,
	approval_status bool NULL,
	approved_by varchar(50) NULL,
	approved_date timestamp NULL,
	approval_id int8 null,
	CONSTRAINT schedule_mc_stop_sequences_stg_pk PRIMARY KEY (schedule_id, stop_office_id, departure_time)
);
CREATE TABLE carriermgmt.schedule_mc_stop_sequence_stg (
	schedule_id int8 NOT NULL,
	sequence_number int8 NOT NULL,
	stop_office_id int8 NOT NULL,
	stop_office_name varchar(50) NOT NULL,
	next_stop_office_id int8 NOT NULL,
	next_stop_office_name varchar(50) NOT NULL,
	distance_to_next_stop float8 NOT NULL,
	distance_unit varchar(10) NOT NULL,
	transit_day int4 NOT NULL,
	transit_hour int2 NOT NULL,
	transit_minute int2 NOT NULL,
	stay_duration_day int8 NOT NULL,
	stay_duration_hour int2 NOT NULL,
	stay_duration_minute int2 NOT NULL,
	departure_time time NOT NULL,
	arrival_time time NOT NULL,
	created_by varchar(50) NOT NULL,
	created_date timestamp DEFAULT now() NOT NULL,
	updated_by varchar(50) NULL,
	updated_date timestamp NULL,
	deleted_by varchar(50) NULL,
	deleted_date timestamp NULL,
	cut_of_time int4 NULL,
	office_location_latitude numeric(10, 8) NULL,
	office_location_longitude numeric(10, 8) NULL,
	approval_status bool NULL,
	approved_by varchar(50) NULL,
	approved_date timestamp NULL,
	approval_id int8 null,
	CONSTRAINT staging_mc_schedule_stop_sequence_pk PRIMARY KEY (schedule_id, stop_office_id, next_stop_office_id, departure_time)
);
CREATE TABLE carriermgmt.schedule_mc_stop_sequence (
	schedule_id int8 NOT NULL,
	sequence_number int8 NOT NULL,
	stop_office_id int8 NOT NULL,
	stop_office_name varchar(50) NOT NULL,
	next_stop_office_id int8 NOT NULL,
	next_stop_office_name varchar(50) NOT NULL,
	distance_to_next_stop float8 NOT NULL,
	distance_unit varchar(10) NOT NULL,
	transit_day int4 NOT NULL,
	transit_hour int2 NOT NULL,
	transit_minute int2 NOT NULL,
	stay_duration_day int8 NOT NULL,
	stay_duration_hour int2 NOT NULL,
	stay_duration_minute int2 NOT NULL,
	departure_time time NOT NULL,
	arrival_time time NOT NULL,
	created_by varchar(50) NOT NULL,
	created_date timestamp DEFAULT now() NOT NULL,
	updated_by varchar(50) NULL,
	updated_date timestamp NULL,
	deleted_by varchar(50) NULL,
	deleted_date timestamp NULL,
	cut_of_time int4 NULL,
	office_location_latitude numeric(10, 8) NULL,
	office_location_longitude numeric(10, 8) NULL,
	approval_status bool NULL,
	approved_by varchar(50) NULL,
	approved_date timestamp NULL,
	approval_id int8 null,
	CONSTRAINT schedule_mc_stop_sequence_pk PRIMARY KEY (schedule_id, stop_office_id, next_stop_office_id, departure_time)
);